import Link from "next/link";
import Head from "next/head";
const Layout = ({ children, title = "Crypto Price Tracker" }) => {
  return (
    <div className="layout">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/bitcoin.ico" />
        <meta http-equiv="refresh" content="10" />
      </Head>
      <header className="header">
        <Link href="/" passHref>
          <a>
            <img src="/logo.png" alt="logo" height="96px" width="96px" />
          </a>
        </Link>
      </header>
      <main>{children}</main>
    </div>
  );
};

export default Layout;
